#!/usr/bin/env node
// Vendors the Lucide icons CardForge uses into js/icons.js.
// Source: lucide-static (ISC) installed in the workspace root node_modules.
// Run: node scripts/generate-icons.mjs
// Regenerate whenever EMOJI_ICON or EXTRA_ICONS changes.
//
// EMOJI_ICON mirrors rush-q-cards-site/scripts/generate-icons.mjs so legacy
// Rush Q card data (emoji field) previews identically here.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LUCIDE_DIRS = [
  join(ROOT, 'node_modules/lucide-static/icons'),
  join(ROOT, '../node_modules/lucide-static/icons'),
];

// emoji (as it appears in legacy card data) → lucide icon name
const EMOJI_ICON = {
  '🧢': 'cloud-lightning',
  '📈': 'trending-up',
  '📣': 'megaphone',
  '💡': 'lightbulb',
  '📦': 'package',
  '🔧': 'wrench',
  '‼️': 'octagon-alert',
  '🌱': 'sprout',
  '🩸': 'heart-crack',
  '🔍': 'search',
  '🔎': 'search',
  '📝': 'notebook-pen',
  '🚀': 'rocket',
  '🏗️': 'building-2',
  '🔄': 'refresh-cw',
  '📊': 'chart-column',
  '🔥': 'flame',
  '🎰': 'dices',
  '🧪': 'flask-conical',
  '👥': 'users',
  '💪': 'biceps-flexed',
  '🤝': 'handshake',
  '🎯': 'target',
  '❄️': 'snowflake',
  '📋': 'clipboard-list',
  '🛠️': 'hammer',
  '☕': 'coffee',
  '👔': 'briefcase-business',
  '🗄️': 'archive',
  '📅': 'calendar-days',
  '😰': 'frown',
  '🏛️': 'landmark',
  '💳': 'credit-card',
  '🦸': 'wand-sparkles',
  '✨': 'sparkles',
  '💫': 'sparkles',
  '🌀': 'refresh-ccw',
  '📢': 'megaphone',
  '📖': 'book-open',
  '🎉': 'party-popper',
  '🛡️': 'shield',
  '✂️': 'scissors',
  '⚖️': 'scale',
  '🔒': 'lock',
  '🗺️': 'map',
  '🩹': 'bandage',
  '🔬': 'microscope',
  '📟': 'radio',
  '⚠️': 'triangle-alert',
  '⚠': 'triangle-alert',
  '🐍': 'worm',
  '🌅': 'sunset',
  '💸': 'banknote',
  '💵': 'banknote',
  '💰': 'coins',
  '🚧': 'construction',
  '🔀': 'shuffle',
  '📤': 'upload',
  '🏈': 'goal',
  '⚔️': 'swords',
  '🎲': 'dice-5',
  '🛑': 'hand',
  '🥊': 'shield-minus',
  '🧩': 'puzzle',
  '🌉': 'link',
  '⚡': 'zap',
  '🚨': 'siren',
  '🐅': 'cat',
  '🙏': 'hand-helping',
  '👈': 'arrow-big-left',
  '📜': 'scroll',
  '🤐': 'volume-x',
  '👑': 'crown',
  '🎶': 'music',
  '🧨': 'bomb',
  '⛱️': 'umbrella',
  '💬': 'message-circle',
  '💻': 'laptop',
  '✅': 'check',
  '✓': 'check',
  '❌': 'x',
  '✗': 'x',
  '✕': 'x',
  '🏆': 'trophy',
  '🤖': 'bot',
  '⭐': 'star',
  '🌟': 'star',
  '★': 'star',
  '👤': 'user',
  '⚙': 'settings',
  '🧭': 'compass',
  '🎮': 'gamepad-2',
  '🎭': 'drama',
  '💀': 'skull',
  '🛌': 'bed',
  '🔮': 'telescope',
  '🔌': 'unplug',
  '🗂': 'layout-grid',
  '☰': 'menu',
  '☺': 'smile',
  '♛': 'crown',
  '🥇': 'medal',
  '🥈': 'medal',
  '🥉': 'medal',
  '🃏': 'square-asterisk',
};

// icons referenced directly by name: CardForge UI + example templates
const EXTRA_ICONS = [
  // UI chrome
  'plus', 'pencil', 'trash-2', 'copy', 'download', 'grip-vertical',
  'image', 'palette', 'layout-template', 'file-json', 'type', 'hash',
  'list', 'settings-2', 'check', 'circle', 'info', 'eye', 'chevron-down',
  // stat pips + template glyphs
  'gem', 'castle', 'heart', 'toy-brick', 'heart-handshake', 'languages',
  'hourglass', 'ruler', 'ban', 'repeat', 'timer', 'play',
];

const dir = LUCIDE_DIRS.find(d => { try { readdirSync(d); return true; } catch { return false; } });
if (!dir) { console.error('lucide-static not found — npm i -D lucide-static'); process.exit(1); }

const names = [...new Set([...Object.values(EMOJI_ICON), ...EXTRA_ICONS])].sort();
const available = new Set(readdirSync(dir).map(f => f.replace(/\.svg$/, '')));
const missing = names.filter(n => !available.has(n));
if (missing.length) { console.error('Missing lucide icons:', missing.join(', ')); process.exit(1); }

const inner = {};
for (const n of names) {
  const svg = readFileSync(join(dir, n + '.svg'), 'utf8');
  inner[n] = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<svg[\s\S]*?>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const out = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Icons: Lucide (https://lucide.dev) — ISC License.
// SVG icon registry: every built-in visual symbol comes from here.

export const ICONS = ${JSON.stringify(inner, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, '\n}')};

export const ICON_NAMES = Object.keys(ICONS);

// emoji → icon name, so legacy card data (emoji fields) needs no migration
export const EMOJI_ICON = ${JSON.stringify(EMOJI_ICON, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, '\n}')};

/**
 * Inline SVG for an icon name. Safe to interpolate into innerHTML templates.
 * @param {string} name lucide icon name (must exist in ICONS)
 * @param {{cls?: string, label?: string}} [opts] extra class / aria-label
 */
export function icon(name, opts = {}) {
  const body = ICONS[name] || ICONS['circle'];
  const cls = 'ic ic-' + name + (opts.cls ? ' ' + opts.cls : '');
  const aria = opts.label
    ? \`role="img" aria-label="\${opts.label}"\`
    : 'aria-hidden="true"';
  return \`<svg class="\${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${aria}>\${body}</svg>\`;
}

/**
 * Inline SVG for a legacy emoji glyph. Unknown emojis fall back to the
 * generic card-back icon.
 */
export function iconForEmoji(emoji, opts = {}) {
  const key = (emoji || '').trim();
  const name = EMOJI_ICON[key] || EMOJI_ICON[key.replace(/\\uFE0F/g, '')] || 'square-asterisk';
  return icon(name, opts);
}

export function hasIcon(name) { return Object.prototype.hasOwnProperty.call(ICONS, name); }
`;

writeFileSync(join(ROOT, 'js/icons.js'), out);
console.log(`Wrote js/icons.js — ${names.length} icons, ${Object.keys(EMOJI_ICON).length} emoji mappings.`);
